apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge-cache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edge-cache
  template:
    metadata:
      labels:
        app: edge-cache
    spec:
      containers:
      - name: edge-cache
        image: netflix-edge-cache:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: edge-cache
spec:
  selector:
    app: edge-cache
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
